[package]
name = "wcal"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.31"
dirs = "4.0.0"
num-traits = "0.2.17"
structopt = "0.3.26"
yansi = "0.5.1"
