[package]
name = "season-date"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
crossterm = "0.20.0"
enum-map = "1.1.1"
num-traits = "0.2.14"
structopt = "0.3.21"
yansi = "0.5.0"
