[package]
name = "scal"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
chrono = "0.4.19"
num-traits = "0.2.14"
structopt = "0.3.21"
yansi = "0.5.0"
